variables:
- name: one
  value: initialValue 


parameters:
- name: parameterBla
  displayName: theDisplayedName
  type: string
  default: null
  values:
    - null
    - 123
    - 456


trigger: none

jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.14', 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - script: |
      echo ${{ variables.one }} # outputs initialValue
      echo $(one)
      echo $(two)
    displayName: First variable pass
  - script: echo '##vso[task.setvariable variable=one]secondValue'
    displayName: Set new variable value
  - script: |
      echo ${{ variables.one }} # outputs initialValue
      echo $(one) # outputs secondValue
    displayName: Second variable pass
  - template: template.yml
    parameters:
      param: ["a", "b"]
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - script: pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - script: python --version
    displayName: 'Display python version'
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: pip install requests
    displayName: 'Install requests'
  - script: |
      pytest tests/test_for_azure_pipeline.py --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
    displayName: 'Test with pytest'
  - task: PythonScript@0
    displayName: 'Post notebook to SUT'
    inputs:
      scriptSource: inline
      script: |
        # todo: consider splitting post test, run test, get testresult into seperate steps
        # todo: consider extracting to file
        import argparse
        import sys
        import traceback
        # external modules
        import requests


        parser = argparse.ArgumentParser()
        parser.add_argument("--testcase_notebook", help="Provide the name of the notebook you want to execute.")
        args = parser.parse_args()
        print ('Running notebook ', args.testcase_notebook)

        # setup http request content
        sut_url = 'http://localhost:23001/travelRequest'
        auth_token = 'abcd1234'
        header = {'Authorization': 'Bearer ' + auth_token}
        data = {'notebook': 'notebook.py'}
        
        # post test notebook to SUT
        try:
          response = requests.post(sut_url, json=data, headers=header)
          print(response)
        except requests.exceptions.ConnectionError:
          print('unable to post notebook')
          # sys.exit(1)
        except:
          traceback.print_exc()
          sys.exit(1)

        # post execution command
        try:
          response = requests.post(sut_url, json=data, headers=header)
          print(response)
        except requests.exceptions.ConnectionError:
          print('unable to execute remote command')
          sys.exit(1)
        except:
          traceback.print_exc()
          sys.exit(1)

        # get test results
        # todo: figure out, when the test results are available
        try:
          response = requests.get(sut_url, headers=header)
          print(response)
        except requests.exceptions.ConnectionError:
          print('unable to get test results')
          sys.exit(1)
        except:
          traceback.print_exc()
          sys.exit(1)
        
        # todo: assess test results
        
      arguments: --testcase_notebook my_testcase_notebook.py
