# Starter pipeline

trigger:
- azure-pipelines-tutorial

jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.14', 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - script: pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - script: python --version
    displayName: 'Display python version'
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: ls tests
    displayName: 'Display folder content'
  - script: |
      pytest tests/test_for_azure_pipeline.py --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
    displayName: 'Test with pytest'
  - task: PythonScript@0
    inputs:
      scriptSource: inline
      script: |
        import sys
        print ('Executing script file is:', str(sys.argv[0]))
        print ('The arguments are:', str(sys.argv))
        import argparse
        parser = argparse.ArgumentParser()
        parser.add_argument("--world", help="Provide the name of the world to greet.")
        args = parser.parse_args()
        print ('Hello ', args.world)
      arguments: --world Venus
